### ISSUE TITLE
1.18.x 버전에서 newInstance 사용 불가능

### ISSUE THREAD

**Issue by MINUTE1084** [MINUTE1084/LAbility#1]
콘솔 전문
```
org.luaj.vm2.LuaError: @plugins\LAbility\rule.lua:17 vm error: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemStack
        at org.luaj.vm2.lib.jse.LuajavaLib.invoke(Unknown Source) ~[?:?]
        at org.luaj.vm2.LuaValue.invoke(Unknown Source) ~[?:?]
        at com.LAbility.LuaUtility.LuaAbilityLoader$3.invoke(LuaAbilityLoader.java:183) ~[?:?]
        at com.LAbility.LuaUtility.LuaAbilityLoader$3.invoke(LuaAbilityLoader.java:154) ~[?:?]
        at org.luaj.vm2.lib.VarArgFunction.call(Unknown Source) ~[?:?]
        at org.luaj.vm2.LuaClosure.execute(Unknown Source) ~[?:?]
        at org.luaj.vm2.LuaClosure.call(Unknown Source) ~[?:?]
        at com.LAbility.LuaUtility.LuaAbilityLoader.LoadLuaRules(LuaAbilityLoader.java:95) ~[?:?]
        at com.LAbility.LAbilityMain.onEnable(LAbilityMain.java:32) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:941) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at org.bukkit.Bukkit.reload(Bukkit.java:749) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:806) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:453) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.ItemStack
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.luaj.vm2.lib.jse.LuajavaLib.classForName(Unknown Source) ~[?:?]
```

1.18.x 버전에서 실행 시 newInstance 메소드가 작동하지 않음 (ClassNotFoundException)
비슷한 메소드인 import의 경우 잘 작동함

시도해본 해결 방안 (해결 안됨)
- jdk 변경 후 빌드
- bukkit api 포함 빌드

원인 해결 전까진 주요 버전 1.17.x에서 개발하는 방향으로 진행

**Comment by MINUTE1084** [comment]
luaj의 문제였던 것으로 추정됨...
1.18.1로 올라오면서, 버킷 API가 외부 라이브러리 형식으로 변경되었는데
luaj의 newInstance는 외부 라이브러리를 못 불러오는 형식으로 작성되어 있었던 것 같음

luaj에서 newInstance가 외부 라이브러리를 불러올 수 있도록 수정 후, 빌드하여 사용하는 방식으로 진행하였던 정상작동하는 것을 확인함.

이슈가 해결되었으므로 이슈를 닫음.
